package com.greendelta.collaboration.model;

public enum Notification {

	GROUP_DELETED,
	REPOSITORY_CREATED,
	REPOSITORY_MOVED,
	REPOSITORY_DELETED,
	DATA_PUSHED,
	ADDED_GROUP_MEMBER,
	ADDED_TO_GROUP_MEMBERS,
	REMOVED_GROUP_MEMBER,
	REMOVED_FROM_GROUP_MEMBERS,
	ADDED_REPOSITORY_MEMBER,
	ADDED_TO_REPOSITORY_MEMBERS,
	REMOVED_REPOSITORY_MEMBER,
	REMOVED_FROM_REPOSITORY_MEMBERS,
	ADDED_TEAM_MEMBER,
	ADDED_TO_TEAM_MEMBERS,
	REMOVED_TEAM_MEMBER,
	REMOVED_FROM_TEAM_MEMBERS,
	USER_CREATED,
	USER_DELETED,
	TEAM_CREATED,
	TEAM_DELETED,
	GROUP_CREATED,
	GROUP_ROLE_CHANGED,
	GROUP_ROLE_OF_MEMBER_CHANGED,
	REPOSITORY_ROLE_CHANGED,
	REPOSITORY_ROLE_OF_MEMBER_CHANGED,
	NOTIFY_FOR_ALL, // also notify about events when not member
	FIELD_COMMENTED,
	TASK_STARTED,
	TASK_ASSIGNED,
	TASK_REVOKED,
	TASK_CANCELED,
	TASK_COMPLETED,
	USER_REGISTERED,
	GROUP_SIZE_LIMIT_EXCEEDED;

}
