define(function(require,exports,module){ function pug_attr(t,e,n,r){if(!1===e||null==e||!e&&("class"===t||"style"===t))return"";if(!0===e)return" "+(r?t:t+'="'+t+'"');var f=typeof e;return"object"!==f&&"function"!==f||"function"!=typeof e.toJSON||(e=e.toJSON()),"string"==typeof e||(e=JSON.stringify(e),n||-1===e.indexOf('"'))?(n&&(e=pug_escape(e))," "+t+'="'+e+'"'):" "+t+"='"+e.replace(/'/g,"&#39;")+"'"}
function pug_classes(s,r){return Array.isArray(s)?pug_classes_array(s,r):s&&"object"==typeof s?pug_classes_object(s):s||""}
function pug_classes_array(r,a){for(var s,e="",u="",c=Array.isArray(a),g=0;g<r.length;g++)(s=pug_classes(r[g]))&&(c&&a[g]&&(s=pug_escape(s)),e=e+u+s,u=" ");return e}
function pug_classes_object(r){var a="",n="";for(var o in r)o&&r[o]&&pug_has_own_property.call(r,o)&&(a=a+n+o,n=" ");return a}
function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_has_own_property=Object.prototype.hasOwnProperty;
var pug_match_html=/["&<>]/;function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;;var locals_for_with = (locals || {});(function (formatDateOrTime, formatTimeOrDate, message, username) {var isOwnMessage = message.from.username===username;
pug_html = pug_html + "\u003Cdiv" + (pug_attr("class", pug_classes(["message-wrapper",isOwnMessage?'right':'left'], [false,true]), false, false)+pug_attr("id", message.id, true, false)) + "\u003E";
if (message.team && !isOwnMessage) {
pug_html = pug_html + "\u003Cdiv\u003E\u003Cstrong\u003E" + (pug_escape(null == (pug_interp = message.from.name) ? "" : pug_interp)) + "\u003C\u002Fstrong\u003E\u003C\u002Fdiv\u003E";
}
pug_html = pug_html + ("\u003Cspan\u003E" + (pug_escape(null == (pug_interp = message.text) ? "" : pug_interp)) + "&nbsp; &nbsp;\u003C\u002Fspan\u003E\u003Csmall" + (" class=\"date\""+pug_attr("title", formatDateOrTime(message.date), true, false)) + "\u003E" + (pug_escape(null == (pug_interp = formatTimeOrDate(message.date)) ? "" : pug_interp)));
if (isOwnMessage) {
pug_html = pug_html + " \u003Cspan" + (pug_attr("class", pug_classes(["glyphicon","glyphicon-ok","read-indicator",!message.team&&message.readDate?'is-read':null], [false,false,false,true]), false, false)) + "\u003E\u003C\u002Fspan\u003E";
}
pug_html = pug_html + "\u003C\u002Fsmall\u003E\u003C\u002Fdiv\u003E\u003Cdiv class=\"clear\"\u003E\u003C\u002Fdiv\u003E";}.call(this,"formatDateOrTime" in locals_for_with?locals_for_with.formatDateOrTime:typeof formatDateOrTime!=="undefined"?formatDateOrTime:undefined,"formatTimeOrDate" in locals_for_with?locals_for_with.formatTimeOrDate:typeof formatTimeOrDate!=="undefined"?formatTimeOrDate:undefined,"message" in locals_for_with?locals_for_with.message:typeof message!=="undefined"?message:undefined,"username" in locals_for_with?locals_for_with.username:typeof username!=="undefined"?username:undefined));;return pug_html;} return template; });