jersey.resource.packages=com.greendelta.cloud.webservice
repository.path=/opt/cloud/repository
database.path=/opt/cloud/database
persistence.unit=prod
base.url=https://cloud.openlca.org
mail.user=cloud@greendelta.com
mail.pass=12345Sechs
mail.proto=smtps
mail.host=ssl0.ovh.net
mail.port=465
mail.ssl=true
mail.tls=false
mail.defaultFrom="LCA Cloud" <no-reply@cloud.openlca.org>