repository.path=/opt/collab/repository
database.path=/opt/collab/database
library.path=/opt/collab/libraries
search.path=/opt/collab/search
base.url=http://localhost:8080
twofactor.servername=openLCA Collaboration Server
mail.user=collab@greendelta.com
mail.pass=12345sechs
mail.proto=smtps
mail.host=ssl0.ovh.net
mail.port=465
mail.ssl=true
mail.tls=false
mail.defaultFrom="LCA Collaboration Server" <no-reply@greendelta.com>
mail.defaultReplyTo="LCA Collaboration Server" <collab@greendelta.com>
imprint.company=GreenDelta GmbH
imprint.ceo=Dr. Andreas Ciroth
imprint.street=Muellerstrasse 135
imprint.zipCode=13349
imprint.city=Berlin
imprint.country=Germany
imprint.phone=+49 (0) 30 4849 6030
imprint.fax=+ 49 (0) 30 4849 6991
imprint.email=gd@greendelta.com
imprint.website=http://www.greendelta.com
imprint.registration=HRB 92350 AG Charlottenburg
imprint.vat=DE813972343
jersey.resource.packages=com.greendelta.collaboration.webservice
persistence.unit=prod