repository.path=/opt/collab/repositories
database.path=/opt/collab/database
library.path=/opt/collab/libraries
<<<<<<< HEAD
#search.path=/opt/collab/search
=======
>>>>>>> cbc7b363295df08d169ca19526d2fc5541accf36
search.cluster=elasticsearch
search.host=localhost
search.index=collaboration-server
base.url=http://localhost:8080
twofactor.servername=openLCA Collaboration Server
mail.user=collab@greendelta.com
mail.pass=12345sechs
mail.proto=smtps
mail.host=ssl0.ovh.net
mail.port=465
mail.ssl=true
mail.tls=false
mail.defaultFrom="LCA Collaboration Server" <lca-digital-commons@listserv.nal.usda.gov>
mail.defaultReplyTo="LCA Collaboration Server" <lca-digital-commons@listserv.nal.usda.gov>
imprint.company=LCA Digital Commons
imprint.ceo=National Agricultural Library
imprint.street=10301 Baltimore Avenue
imprint.zipCode=20705
imprint.city=Beltsville
imprint.country=MD
imprint.phone=+49 (0) 30 4849 6030
imprint.fax=+ 49 (0) 30 4849 6991
imprint.email=lca-digital-commons@listserv.nal.usda.gov
imprint.website=https://www.lcacommons.gov
imprint.registration=
imprint.vat=
jersey.resource.packages=com.greendelta.collaboration.webservice
persistence.unit=prod
