spring.datasource.url=jdbc:mysql://localhost:3306/collaboration-server?create=true
spring.datasource.username=collaboration-server
spring.datasource.password=collaboration-server
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=validate
spring.security.filter.dispatcher-types=REQUEST, ERROR