#appenders references
appenders=console

#defining console
appender.console.type = Console
appender.console.name = consoleOutput
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy-MM-dd HH:mm:ss:SSS} %-5p %c:%L - %m%n

rootLogger.level = info

#rootLogger.appenderReferences 
rootLogger.appenderRefs = console

#assigning rootLogger appender to myOutput
rootLogger.appenderRef.console.ref = consoleOutput