define () ->

	init: () ->
		return {
			'': 'landingPage'
			'search(/:query)': 'search'
			'repository/new(/:group)': 'repositoryNew'
			'repository/import(/:group)': 'repositoryImport'
			'repository/import-json(/:group)': 'repositoryImportJson'
			'repository/import-external': 'repositoryImportExternal'
			'user': 'userProfile'
			'user/profile': 'userProfile'
			'user/messaging': 'userMessaging'
			'user/notifications': 'userNotifications'
			'dashboard': 'dashboardActivities'
			'dashboard/activities': 'dashboardActivities'
			'dashboard/repositories': 'dashboardRepositories'
			'dashboard/groups': 'dashboardGroups'
			'dashboard/libraries': 'dashboardLibraries'
			'dashboard/libraries/add': 'dashboardAddLibrary'
			'dashboard/tags': 'dashboardTags'
			'administration': 'adminOverview'
			'administration/overview': 'adminOverview'
			'administration/user/new': 'adminUserNew'
			'administration/user/profile/:username': 'adminUserEdit'
			'administration/team/new': 'adminTeamNew'
			'administration/team/profile/:teamname': 'adminTeamEdit'
			'administration/settings': 'adminSettings'
			'administration/maintenance': 'adminMaintenance'
			'messages(/:username)': 'messages'
			'tasks': 'tasks'
			'tasks/review/new': 'reviewManage'
			'tasks/review/:id': 'reviewManage'
			'group/new': 'groupNew'
			'groups/:group': 'groupInfo'
			'groups/:group/tags': 'groupTags'
			'groups/:group/members': 'groupMembers'	
			'error(/:statuscode)':'error'
			':group/:name': 'repositoryInfo'
			':group/:name/activities': 'repositoryActivities'
			':group/:name/datasets(/*categoryPath)(?commitId=:commitId)': 'repositoryDatasets'
			':group/:name/dataset/:type/:refId(?:query)': 'repositoryDataset'
			':group/:name/commits(?:query)': 'repositoryCommits'
			':group/:name/commit/:commitId(?:query)': 'repositoryCommit'
			':group/:name/comments': 'repositoryComments'
			':group/:name/releases(?:query)': 'repositoryCommits'
			':group/:name/release/:commitId(?:query)': 'repositoryCommit'
			':group/:name/tags': 'repositoryTags'
			':group/:name/members': 'repositoryMembers'
			'*path':'notFound'
		}
