define
	'': 'dashboardRepositories'
	'repository/new': 'repositoryNew'
	'user': 'userProfile'
	'user/profile': 'userProfile'
	'dashboard': 'dashboardRepositories'
	'dashboard/repositories': 'dashboardRepositories'
	'dashboard/groups': 'dashboardGroups'
	'administration': 'adminOverview'
	'administration/overview': 'adminOverview'
	'administration/user/new': 'adminUserNew'
	'administration/user/profile/:username': 'adminUserEdit'
	'administration/team/new': 'adminTeamNew'
	'administration/team/profile/:teamname': 'adminTeamEdit'
	'group/new': 'groupNew'
	'groups/:group': 'groupInfo'
	'groups/:group/members': 'groupMembers'	
	':group/:name': 'repositoryInfo'
	':group/:name/datasets(/:categoryId)': 'repositoryDatasets'
	':group/:name/dataset/:type/:refId': 'repositoryDataset'
	':group/:name/dataset/:type/:refId(/:commitId)': 'repositoryDataset'
	':group/:name/commits': 'repositoryCommits'
	':group/:name/commit/:commitId': 'repositoryCommit'
	':group/:name/members': 'repositoryMembers'
	'403':'noAccess'
	'*path':'notFound'
