define
	'user': 'userProfile'
	'user/profile': 'userProfile'
	'repository/new': 'repositoryNew'
	'repository/:group/:name': 'repositoryInfo'
	'repository/datasets/:group/:name(/:categoryId)': 'repositoryDatasets'
	'dashboard': 'dashboardRepositories'
	'dashboard/repositories': 'dashboardRepositories'
	'admin': 'adminOverview'
	'admin/overview': 'adminOverview'
	'admin/user/new': 'adminUserNew'
	'admin/user/profile/:username': 'adminUserEdit'
	'admin/repository/new': 'adminRepositoryNew'
	'admin/repository/:group/:name': 'adminRepositoryInfo'
	'*path': 'dashboardRepositories'