define
	'': 'dashboardRepositories'
	'search(/:query)': 'search'
	'repository/new(/:group)': 'repositoryNew'
	'user': 'userProfile'
	'user/profile': 'userProfile'
	'user/messaging': 'userMessaging'
	'user/notifications': 'userNotifications'
	'dashboard': 'dashboardRepositories'
	'dashboard/repositories': 'dashboardRepositories'
	'dashboard/groups': 'dashboardGroups'
	'administration': 'adminOverview'
	'administration/overview': 'adminOverview'
	'administration/user/new': 'adminUserNew'
	'administration/user/profile/:username': 'adminUserEdit'
	'administration/team/new': 'adminTeamNew'
	'administration/team/profile/:teamname': 'adminTeamEdit'
	'administration/libraries': 'adminLibraries'
	'messages(/:username)': 'messages'
	'tasks': 'tasks'
	'tasks/review/new': 'reviewManage'
	'tasks/review/:id': 'reviewManage'
	'group/new': 'groupNew'
	'groups/:group': 'groupInfo'
	'groups/:group/members': 'groupMembers'	
	'error(/:statuscode)':'error'
	':group/:name': 'repositoryInfo'
	':group/:name/datasets': 'repositoryDatasets'
	':group/:name/datasets/*categoryPath': 'repositoryDatasets'
	':group/:name/dataset/:type/:refId(/:commitId)(/:commentPath)': 'repositoryDataset'
	':group/:name/commits': 'repositoryCommits'
	':group/:name/commit/:commitId': 'repositoryCommit'
	':group/:name/comments': 'repositoryComments'
	':group/:name/members': 'repositoryMembers'
	'*path':'notFound'
