CREATE TABLE IF NOT EXISTS release_info (
  id BIGINT NOT NULL,
  repository_path VARCHAR(255),
  commit_id VARCHAR(255),
  tags VARCHAR(255),
  label VARCHAR(255),
  version VARCHAR(255),
  description VARCHAR(4000),
  source_info VARCHAR(1000),
  contact_info VARCHAR(1000),
  change_log VARCHAR(1000),
  project_info VARCHAR(1000),
  project_funding VARCHAR(1000),
  appropriate_use VARCHAR(4000),
  dq_assessment VARCHAR(1000),
  citation VARCHAR(1000),
  type_of_data VARCHAR(64),
  PRIMARY KEY (id)
) engine = InnoDB;

ALTER TABLE comment MODIFY model_type ENUM('PROJECT', 'IMPACT_METHOD', 'IMPACT_CATEGORY', 'PRODUCT_SYSTEM', 'PROCESS', 'FLOW', 'FLOW_PROPERTY', 'UNIT_GROUP', 'ACTOR', 'SOURCE', 'CATEGORY', 'LOCATION', 'SOCIAL_INDICATOR', 'CURRENCY', 'PARAMETER', 'DQ_SYSTEM', 'RESULT', 'EPD');
ALTER TABLE comment MODIFY restricted_to_role ENUM('NONE', 'READER', 'CONTRIBUTOR', 'REVIEWER', 'EDITOR', 'RELEASE_MANAGER', 'OWNER');
ALTER TABLE job MODIFY type ENUM('RESET_PASSWORD');
ALTER TABLE membership MODIFY role ENUM('NONE', 'READER', 'CONTRIBUTOR', 'REVIEWER', 'EDITOR', 'RELEASE_MANAGER', 'OWNER');
ALTER TABLE review_reference MODIFY type ENUM('PROJECT', 'IMPACT_METHOD', 'IMPACT_CATEGORY', 'PRODUCT_SYSTEM', 'PROCESS', 'FLOW', 'FLOW_PROPERTY', 'UNIT_GROUP', 'ACTOR', 'SOURCE', 'CATEGORY', 'LOCATION', 'SOCIAL_INDICATOR', 'CURRENCY', 'PARAMETER', 'DQ_SYSTEM', 'RESULT', 'EPD');
ALTER TABLE review MODIFY state ENUM('CREATED', 'PROCESSING', 'VERIFYING', 'CANCELED', 'COMPLETED');
ALTER TABLE setting MODIFY type ENUM('SERVER_SETTING', 'IMPRINT_SETTING', 'MAIL_SETTING', 'SEARCH_SETTING', 'SEARCH_INDEX', 'REPOSITORY_SETTING', 'GROUP_SETTING', 'LIBRARY_SETTING');
ALTER TABLE team MODIFY avatar MEDIUMBLOB;
ALTER TABLE user MODIFY avatar MEDIUMBLOB;
ALTER TABLE user ADD COLUMN library_manager BIT(1);

DROP TABLE IF EXISTS restriction_set;

UPDATE user SET library_manager = admin = 1 OR data_manager = 1;