define(function(require,exports,module){ function pug_attr(t,e,n,r){if(!1===e||null==e||!e&&("class"===t||"style"===t))return"";if(!0===e)return" "+(r?t:t+'="'+t+'"');var f=typeof e;return"object"!==f&&"function"!==f||"function"!=typeof e.toJSON||(e=e.toJSON()),"string"==typeof e||(e=JSON.stringify(e),n||-1===e.indexOf('"'))?(n&&(e=pug_escape(e))," "+t+'="'+e+'"'):" "+t+"='"+e.replace(/'/g,"&#39;")+"'"}
function pug_classes(s,r){return Array.isArray(s)?pug_classes_array(s,r):s&&"object"==typeof s?pug_classes_object(s):s||""}
function pug_classes_array(r,a){for(var s,e="",u="",c=Array.isArray(a),g=0;g<r.length;g++)(s=pug_classes(r[g]))&&(c&&a[g]&&(s=pug_escape(s)),e=e+u+s,u=" ");return e}
function pug_classes_object(r){var a="",n="";for(var o in r)o&&r[o]&&pug_has_own_property.call(r,o)&&(a=a+n+o,n=" ");return a}
function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_has_own_property=Object.prototype.hasOwnProperty;
var pug_match_html=/["&<>]/;function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;;var locals_for_with = (locals || {});(function (errorMessage, imageSrc, stacktrace, statuscode) {pug_html = pug_html + "\u003Cdiv" + (pug_attr("class", pug_classes(["error-page",stacktrace?'stacktrace':null], [false,true]), false, false)) + "\u003E\u003Cimg" + (pug_attr("src", imageSrc, true, false)+" aria-label=\"Error logo\"") + "\u002F\u003E\u003Ch1\u003E" + (pug_escape(null == (pug_interp = statuscode?statuscode:'Client error') ? "" : pug_interp)) + "\u003C\u002Fh1\u003E\u003Chr\u002F\u003E";
if (stacktrace) {
pug_html = pug_html + "\u003Cbutton class=\"btn btn-default btn-xs pull-right select-text\"\u003ESelect stracktrace\u003C\u002Fbutton\u003E";
}
pug_html = pug_html + "\u003Ch3 class=\"error-message\"\u003E" + (pug_escape(null == (pug_interp = errorMessage) ? "" : pug_interp)) + "\u003C\u002Fh3\u003E\u003C\u002Fdiv\u003E";}.call(this,"errorMessage" in locals_for_with?locals_for_with.errorMessage:typeof errorMessage!=="undefined"?errorMessage:undefined,"imageSrc" in locals_for_with?locals_for_with.imageSrc:typeof imageSrc!=="undefined"?imageSrc:undefined,"stacktrace" in locals_for_with?locals_for_with.stacktrace:typeof stacktrace!=="undefined"?stacktrace:undefined,"statuscode" in locals_for_with?locals_for_with.statuscode:typeof statuscode!=="undefined"?statuscode:undefined));;return pug_html;} return template; });